server:
  port: 8001
spring:
  application:
    name: nacos-getway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.20:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: nacos-getway-provider
          uri: lb://nacos-provider
          predicates:
            - Path=/provider/**
